name: xochuapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.3+3

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  bottom_nav_bar: ^1.0.3
  percent_indicator: ^4.0.0
  shared_preferences: ^2.0.13
  pin_code_fields: ^7.3.0
  provider: ^6.0.2
  http: ^0.13.4
  localize_and_translate: ^4.1.1
  oktoast: ^3.1.5
  flutter_advanced_drawer: ^1.3.0
  intl: ^0.17.0
  flutter_widget_from_html_core: ^0.8.5+1
  expansion_widget: ^0.0.3
  favorite_button: ^0.0.4
  share_plus: ^3.1.0
  google_maps_flutter: ^2.0.3
  youtube_player_flutter: ^8.0.0
  flutter_touch_spin: ^2.0.0
  selectable_container: ^1.0.2
  webview_flutter: ^3.0.1
  bottom_sheet: ^2.0.0
  image_picker: ^0.8.4+10
  adaptive_action_sheet: ^2.0.1
  ndialog: ^4.1.1
  firebase_messaging: ^11.2.11
  firebase_core: ^1.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
     - assets/lang/ru.json
     - assets/lang/en.json
     - assets/images/logo.png
     - assets/images/noavatar.png
     - assets/images/pin.png
     - assets/images/notification.png
     - assets/images/home.png
     - assets/images/coupons.png
     - assets/images/wishlist.png
     - assets/images/cart.png
     - assets/images/soldout.png
     - assets/images/cart-heading.png
     - assets/images/profile.png
     - assets/images/product1.jpg
     - assets/images/product2.jpg
     - assets/images/product3.jpg
     - assets/images/photo.jpg
     - assets/images/about.jpg
     - assets/images/icon1.png
     - assets/images/features1.png
     - assets/images/features2.png
     - assets/images/features3.png
     - assets/images/about-logo.png
     - assets/images/contacts0.png
     - assets/images/contacts1.png
     - assets/images/contacts2.png


  fonts:
     - family: Commissioner
       fonts:
         - asset: assets/fonts/Commissioner-Regular.ttf
         - asset: assets/fonts/Commissioner-Thin.ttf
           weight: 100
         - asset: assets/fonts/Commissioner-ExtraLight.ttf
           weight: 200
         - asset: assets/fonts/Commissioner-Light.ttf
           weight: 300
         - asset: assets/fonts/Commissioner-Medium.ttf
           weight: 500
         - asset: assets/fonts/Commissioner-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Commissioner-Bold.ttf
           weight: 700
         - asset: assets/fonts/Commissioner-ExtraBold.ttf
           weight: 800
         - asset: assets/fonts/Commissioner-Black.ttf
           weight: 900
